// Code generated by "stringer -type=TaskStatus"; DO NOT EDIT.

package taskmodel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NEW-0]
	_ = x[WAITING-1]
	_ = x[SUBMITTED-2]
	_ = x[PROCESSING-3]
	_ = x[DONE-4]
	_ = x[ERROR-5]
	_ = x[FAILED-6]
}

const _TaskStatus_name = "NEWWAITINGSUBMITTEDPROCESSINGDONEERRORFAILED"

var _TaskStatus_index = [...]uint8{0, 3, 10, 19, 29, 33, 38, 44}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
